//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.StretchAr
{
    [Serializable]
    public class HitPosMsg : Message
    {
        public const string k_RosMessageName = "stretch_ar/HitPos";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.Vector3Msg hit_position;
        public Geometry.Vector3Msg controller_position;

        public HitPosMsg()
        {
            this.hit_position = new Geometry.Vector3Msg();
            this.controller_position = new Geometry.Vector3Msg();
        }

        public HitPosMsg(Geometry.Vector3Msg hit_position, Geometry.Vector3Msg controller_position)
        {
            this.hit_position = hit_position;
            this.controller_position = controller_position;
        }

        public static HitPosMsg Deserialize(MessageDeserializer deserializer) => new HitPosMsg(deserializer);

        private HitPosMsg(MessageDeserializer deserializer)
        {
            this.hit_position = Geometry.Vector3Msg.Deserialize(deserializer);
            this.controller_position = Geometry.Vector3Msg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.hit_position);
            serializer.Write(this.controller_position);
        }

        public override string ToString()
        {
            return "HitPosMsg: " +
            "\nhit_position: " + hit_position.ToString() +
            "\ncontroller_position: " + controller_position.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
